const assets = {
    // badges
    "badges": {
        "1_Year_on_CodeJudge": require("./badges/badges_1_1_Year_on_CodeJudge.svg"),
        "2_Years_on_CodeJudge": require("./badges/badges_2_2_Years_on_CodeJudge.svg"),
        "5_Years_on_CodeJudge": require("./badges/badges_3_5_Years_on_CodeJudge.svg"),
        "10_Years_on_CodeJudge": require("./badges/badges_4_10_Years_on_CodeJudge.svg"),
        "15_Years_on_CodeJudge": require("./badges/badges_5_15_Years_on_CodeJudge.svg"),
        "Competitor": require("./badges/badges_6_Competitor.svg"),
        "Getting_Started_Competitor": require("./badges/badges_7_Getting_Started_Competitor.svg"),
        "Research_Competitor": require("./badges/badges_8_Research_Competitor.svg"),
        "Community_Competitor": require("./badges/badges_9_Community_Competitor.svg"),
        "Playground_Competitor": require("./badges/badges_10_Playground_Competitor.svg"),
        "Simulation_Competitor": require("./badges/badges_11_Simulation_Competitor.svg"),
        "Santa_Competitor": require("./badges/badges_12_Santa_Competitor.svg"),
        "March_Mania_Competitor": require("./badges/badges_13_March_Mania_Competitor.svg"),
        "Code_Submitter": require("./badges/badges_14_Code_Submitter.svg"),
        "Submission_Streak": require("./badges/badges_15_Submission_Streak.svg"),
        "Super_Submission_Streak": require("./badges/badges_16_Super_Submission_Streak.svg"),
        "Mega_Submission_Streak": require("./badges/badges_17_Mega_Submission_Streak.svg"),
        "Python_Coder": require("./badges/badges_18_Python_Coder.svg"),
        "R_Coder": require("./badges/badges_19_R_Coder.svg"),
        "R_Markdown_Coder": require("./badges/badges_20_R_Markdown_Coder.svg"),
        "Code_Uploader": require("./badges/badges_21_Code_Uploader.svg"),
        "API_Notebook_Creator": require("./badges/badges_22_API_Notebook_Creator.svg"),
        "Github_Coder": require("./badges/badges_23_Github_Coder.svg"),
        "Colab_Coder": require("./badges/badges_24_Colab_Coder.svg"),
        "Code_Tagger": require("./badges/badges_25_Code_Tagger.svg"),
        "Code_Forker": require("./badges/badges_26_Code_Forker.svg"),
        "Notebook_Modeler": require("./badges/badges_27_Notebook_Modeler.svg"),
        "Utility_Scripter": require("./badges/badges_28_Utility_Scripter.svg"),
        "Dataset_Creator": require("./badges/badges_29_Dataset_Creator.svg"),
        "Dataset_Pipeline_Creator": require("./badges/badges_30_Dataset_Pipeline_Creator.svg"),
        "Linked_Dataset_Creator": require("./badges/badges_31_Linked_Dataset_Creator.svg"),
        "API_Dataset_Creator": require("./badges/badges_32_API_Dataset_Creator.svg"),
        "Dataset_Documenter": require("./badges/badges_33_Dataset_Documenter.svg"),
        "Dataset_Tagger": require("./badges/badges_34_Dataset_Tagger.svg"),
        "Model_Creator": require("./badges/badges_35_Model_Creator.svg"),
        "Model_Variation_Creator": require("./badges/badges_36_Model_Variation_Creator.svg"),
        "Model_Pipeline_Creator": require("./badges/badges_37_Model_Pipeline_Creator.svg"),
        "Linked_Model_Creator": require("./badges/badges_38_Linked_Model_Creator.svg"),
        "Model_Documenter": require("./badges/badges_40_Model_Documenter.svg"),
        "Model_Tagger": require("./badges/badges_41_Model_Tagger.svg"),
        "Competition_Modeler": require("./badges/badges_42_Competition_Modeler.svg"),
        "Stylish": require("./badges/badges_43_Stylish.svg"),
        "Collector": require("./badges/badges_44_Collector.svg"),
        "Bookmarker": require("./badges/badges_45_Bookmarker.svg"),
        "Agent_of_Discord":require("./badges/badges_47_Agent_of_Discord.svg"),
        "Learner": require("./badges/badges_48_Learner.svg"),
        "Student":require("./badges/badges_49_Student.svg"),
        "Graduate":require("./badges/badges_50_Graduate.svg"),
        "Completed_5_Day_Gen_AI_Intensive":require("./badges/badges_51_Completed_5_Day_Gen_AI_Intensive.svg"),
        "Founding_Benchmark_Task_Author":require("./badges/badges_52_Founding_Benchmark_Task_Author.svg"),
        "7_Day_Login_Streak":require("./badges/badges_53_7_Day_Login_Streak.svg"),
        "30_Day_Login_Streak":require("./badges/badges_54_30_Day_Login_Streak.svg"),
        "100_Day_Login_Streak":require("./badges/badges_55_100_Day_Login_Streak.svg"),
        "Year_Long_Login_Streak": require("./badges/badges_56_Year_Long_Login_Streak.svg"),
    },

    // icons
    "icon": {
        "c_c++_logo": require("./icon/c_c++_logo.png"),
        "java_logo": require("./icon/java_logo.png"),
        "javascript-logo": require("./icon/javascript_logo.png"),
        "python_logo": require("./icon/python_logo.png"),
    },

    // homePage
    "homePage": {
        "home_image_1": require("./homePage/home_image_1.png"),
        "home_image_2": require("./homePage/home_image_2.png"),
        "home_image_3": require("./homePage/home_image_3.png"),
        "home_image_4": require("./homePage/home_image_4.png"),
    },

    // default_avatar
    "default_avatar": require("./default_avatar.png"),

    // rank
    "rank": {
        "Unranked": require("./rank/rank_Unranked.png"),
        "Iron_1": require("./rank/rank_Iron_1.png"),
        "Iron_2": require("./rank/rank_Iron_2.png"),
        "Iron_3": require("./rank/rank_Iron_3.png"),
        "Bronze_1": require("./rank/rank_Bronze_1.png"),
        "Bronze_2": require("./rank/rank_Bronze_2.png"),
        "Bronze_3": require("./rank/rank_Bronze_3.png"),
        "Silver_1": require("./rank/rank_Silver_1.png"),
        "Silver_2": require("./rank/rank_Silver_2.png"),
        "Silver_3": require("./rank/rank_Silver_3.png"),
        "Gold_1": require("./rank/rank_Gold_1.png"),
        "Gold_2": require("./rank/rank_Gold_2.png"),
        "Gold_3": require("./rank/rank_Gold_3.png"),
        "Platinum_1": require("./rank/rank_Platinum_1.png"),
        "Platinum_2": require("./rank/rank_Platinum_2.png"),
        "Platinum_3": require("./rank/rank_Platinum_3.png"),
        "Diamond_1": require("./rank/rank_Diamond_1.png"),
        "Diamond_2": require("./rank/rank_Diamond_2.png"),
        "Diamond_3": require("./rank/rank_Diamond_3.png"),
        "Ascendant_1": require("./rank/rank_Ascendant_1.png"),
        "Ascendant_2": require("./rank/rank_Ascendant_2.png"),
        "Ascendant_3": require("./rank/rank_Ascendant_3.png"),
        "Immortal_1": require("./rank/rank_Immortal_1.png"),
        "Immortal_2": require("./rank/rank_Immortal_2.png"),
        "Immortal_3": require("./rank/rank_Immortal_3.png"),
        "Radiant": require("./rank/rank_Radiant.png")
    }
}

export default assets;